version: '3'

services:
    customer:
        ports:
            - '3001:3001'
        build:
            context: .
            dockerfile: Customer.Dockerfile
        container_name: 'customernode'
    seller:
        ports:
            - '3002:3002'
        build:
            context: .
            dockerfile: Seller.Dockerfile
        container_name: 'sellernode'
    product:
        ports:
            - '3003:3003'
        build:
            context: .
            dockerfile: Product.Dockerfile
        container_name: 'productnode'
    
